imprv_url: 
imprv_log_usr: 
# imprv_account_type should be either 'advanced' or 'essential' or 'mss'.
imprv_account_type: 
rivrbed_url: 
rivrbed_usr: 
dom_test: 
win_aprch_url: 
func_val_tr: 
fw_allwd_tr:
web_domain: 
splunk_dom: 
airline_type: 
airline: 
web_dom_pub_ip: 